# filename: ex057.rq

PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

SELECT ?first ?last ?workTel ?email
WHERE
{
  ?s ab:firstName ?first ;
     ab:lastName ?last .
  OPTIONAL 
  { ?s ab:workTel ?workTel . 
   ?s ab:workTel ?email .}
}

