# filename: ex146.rq

PREFIX e: <http://learningsparql.com/ns/expenses#>

SELECT (AVG(?amount) as ?amountAVG)
WHERE
{
  ?meal e:description ?description ;
        e:date ?date ;
        e:amount ?amount . 
}



